runtime: go
api_version: go1

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: _go_app

threadsafe: true

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic